const sights = [
{id:"b1",name:"Ark of Bukhara",type:"place",icon:"🏰",lat:39.7780,lng:64.4098,rating:4.6,reviews:1432,markerColor:"#8B4513",wiki:"Ark_of_Bukhara",desc:"The ancient royal citadel housing Bukhara's emirs for over a millennium. Throne rooms, stables, mosque and prison all inside one massive fortress wall.",tip:"Climb the ramparts at sunset for the best views over the old city.",hours:"9am–10pm daily",fee:"60,000 UZS"},
      {id:"b2",name:"Kalon Minaret",type:"place",icon:"🕌",lat:39.7757,lng:64.4151,rating:4.8,reviews:2318,markerColor:"#8B4513",wiki:"Kalon_Minaret",desc:"47-meter minaret built in 1127, so magnificent Genghis Khan spared it when he razed the city. Every brick pattern is unique. Lit like a candle at night.",tip:"View from the rooftop of Lyabi-Hauz teahouses at golden hour.",hours:"Open 24 hours",fee:"Free (exterior)"},
      {id:"b3",name:"Ismail Samani Mausoleum",type:"place",icon:"⭐",lat:39.7770,lng:64.4006,rating:4.7,reviews:1102,markerColor:"#8B4513",wiki:"Samanid_mausoleum",desc:"Central Asia's oldest surviving Islamic tomb (905 AD). A perfect brick cube whose geometric brick patterns shift and dance with sunlight throughout the day.",tip:"Visit in the morning when low light reveals the brickwork magic.",hours:"8am–6pm daily",fee:"15,000 UZS"},
      {id:"b4",name:"Lyabi-Hauz Square",type:"place",icon:"🌿",lat:39.7730,lng:64.4211,rating:4.7,reviews:1876,markerColor:"#8B4513",wiki:"Lyabi-Hauz",desc:"The ancient reflecting pool at the heart of old Bukhara, shaded by 500-year-old mulberry trees. Locals drink green tea here every single day.",tip:"Sit at the teahouse by the water at sunset with green tea and watch the world pass.",hours:"Open 24 hours",fee:"Free"},
      {id:"b5",name:"Chor Minor",type:"place",icon:"🗼",lat:39.7749,lng:64.4273,rating:4.6,reviews:987,markerColor:"#8B4513",wiki:"Chor_Minor",desc:"Quirky 1807 gatehouse with four turquoise domes, each decorated with a different motif representing the world's religions. The most unusual building in Bukhara.",tip:"Easy to miss but completely worth finding. Ask locals — they know it.",hours:"8am–8pm daily",fee:"15,000 UZS"},
      {id:"b6",name:"Kalon Mosque (Poi-Kalon)",type:"place",icon:"☪️",lat:39.7759,lng:64.4136,rating:4.8,reviews:2043,markerColor:"#8B4513",wiki:"Kalon_Mosque",desc:"The grand 16th-century mosque can hold 12,000 worshippers. Still active for Friday prayers. The enormous courtyard with its 288 domed bays is freely accessible.",tip:"Enter the enormous courtyard for free. Exhibits inside require a ticket.",hours:"9am–6pm daily",fee:"Free courtyard"},
      {id:"b7",name:"Trading Domes (Taki)",type:"place",icon:"🛒",lat:39.7755,lng:64.4160,rating:4.5,reviews:1234,markerColor:"#8B4513",wiki:"Taki_(Bukhara)",desc:"Ancient covered bazaar domes where Silk Road merchants traded spices, jewelry and textiles for centuries. Now filled with ceramics, suzani, and handicrafts.",tip:"Bargaining is expected and enjoyed — start at 60% of the asking price.",hours:"10am–7pm daily",fee:"Free"},
];

export default sights;
