const VF90 = (flag,name) => ({flag,type:"Visa-Free",duration:"90 days",note:`${name} passport holders enjoy 90 days visa-free in Uzbekistan. No prior application needed — just arrive with a valid passport (6+ months remaining validity).`});
const VF30 = (flag,name) => ({flag,type:"Visa-Free",duration:"30 days",note:`${name} passport holders can enter Uzbekistan visa-free for up to 30 days. For longer stays, apply for an e-visa at https://e-visa.gov.uz before extending.`});
const EV  = (flag,name) => ({flag,type:"E-Visa",duration:"30 days",note:`${name} passport holders require an e-visa. Apply online at https://e-visa.gov.uz — costs $20, issued within 2–3 business days. Print or save your e-visa to show on arrival.`});
const VR  = (flag,name) => ({flag,type:"Visa Required",duration:"30 days",note:`${name} passport holders should apply for a visa at the nearest Uzbek embassy or consulate, or try the e-visa portal at https://e-visa.gov.uz. Allow 3-5 business days.`});

const VISA_DATA = {
  // ── NORTH AMERICA ──
  "🇺🇸 United States":    VF90("🇺🇸","US"),
  "🇨🇦 Canada":           VF30("🇨🇦","Canadian"),
  "🇲🇽 Mexico":           VF30("🇲🇽","Mexican"),
  "🇨🇺 Cuba":             VF30("🇨🇺","Cuban"),
  "🇯🇲 Jamaica":          VF30("🇯🇲","Jamaican"),
  "🇭🇹 Haiti":            VR("🇭🇹","Haitian"),
  "🇩🇴 Dominican Republic":VF30("🇩🇴","Dominican"),
  "🇧🇧 Barbados":         VF30("🇧🇧","Barbadian"),
  "🇧🇿 Belize":           VF30("🇧🇿","Belizean"),
  "🇨🇷 Costa Rica":       VF30("🇨🇷","Costa Rican"),
  "🇸🇻 El Salvador":      VF30("🇸🇻","Salvadoran"),
  "🇬🇹 Guatemala":        VF30("🇬🇹","Guatemalan"),
  "🇭🇳 Honduras":         VF30("🇭🇳","Honduran"),
  "🇳🇮 Nicaragua":        VF30("🇳🇮","Nicaraguan"),
  "🇵🇦 Panama":           VF30("🇵🇦","Panamanian"),
  "🇹🇹 Trinidad & Tobago":VF30("🇹🇹","Trinidadian"),
  // ── SOUTH AMERICA ──
  "🇦🇷 Argentina":        VF30("🇦🇷","Argentine"),
  "🇧🇴 Bolivia":          EV("🇧🇴","Bolivian"),
  "🇧🇷 Brazil":           VF30("🇧🇷","Brazilian"),
  "🇨🇱 Chile":            VF30("🇨🇱","Chilean"),
  "🇨🇴 Colombia":         EV("🇨🇴","Colombian"),
  "🇪🇨 Ecuador":          EV("🇪🇨","Ecuadorian"),
  "🇬🇾 Guyana":           EV("🇬🇾","Guyanese"),
  "🇵🇾 Paraguay":         EV("🇵🇾","Paraguayan"),
  "🇵🇪 Peru":             EV("🇵🇪","Peruvian"),
  "🇸🇷 Suriname":         EV("🇸🇷","Surinamese"),
  "🇺🇾 Uruguay":          EV("🇺🇾","Uruguayan"),
  "🇻🇪 Venezuela":        EV("🇻🇪","Venezuelan"),
  // ── WESTERN EUROPE ──
  "🇬🇧 United Kingdom":   VF30("🇬🇧","British"),
  "🇩🇪 Germany":          VF30("🇩🇪","German"),
  "🇫🇷 France":           VF30("🇫🇷","French"),
  "🇮🇹 Italy":            VF30("🇮🇹","Italian"),
  "🇪🇸 Spain":            VF30("🇪🇸","Spanish"),
  "🇵🇹 Portugal":         VF30("🇵🇹","Portuguese"),
  "🇳🇱 Netherlands":      VF30("🇳🇱","Dutch"),
  "🇧🇪 Belgium":          VF30("🇧🇪","Belgian"),
  "🇱🇺 Luxembourg":       VF30("🇱🇺","Luxembourgish"),
  "🇨🇭 Switzerland":      VF30("🇨🇭","Swiss"),
  "🇦🇹 Austria":          VF30("🇦🇹","Austrian"),
  "🇮🇪 Ireland":          VF30("🇮🇪","Irish"),
  "🇩🇰 Denmark":          VF30("🇩🇰","Danish"),
  "🇸🇪 Sweden":           VF30("🇸🇪","Swedish"),
  "🇳🇴 Norway":           VF30("🇳🇴","Norwegian"),
  "🇫🇮 Finland":          VF30("🇫🇮","Finnish"),
  "🇮🇸 Iceland":          VF30("🇮🇸","Icelandic"),
  "🇲🇨 Monaco":           VF30("🇲🇨","Monégasque"),
  "🇱🇮 Liechtenstein":    VF30("🇱🇮","Liechtensteinish"),
  "🇸🇲 San Marino":       VF30("🇸🇲","Sammarinese"),
  "🇻🇦 Vatican City":     VF30("🇻🇦","Vatican"),
  "🇦🇩 Andorra":          VF30("🇦🇩","Andorran"),
  "🇲🇹 Malta":            VF30("🇲🇹","Maltese"),
  "🇨🇾 Cyprus":           VF30("🇨🇾","Cypriot"),
  "🇬🇷 Greece":           VF30("🇬🇷","Greek"),
  // ── CENTRAL / EASTERN EUROPE ──
  "🇵🇱 Poland":           VF30("🇵🇱","Polish"),
  "🇨🇿 Czech Republic":   VF30("🇨🇿","Czech"),
  "🇸🇰 Slovakia":         VF30("🇸🇰","Slovak"),
  "🇭🇺 Hungary":          VF30("🇭🇺","Hungarian"),
  "🇷🇴 Romania":          VF30("🇷🇴","Romanian"),
  "🇧🇬 Bulgaria":         VF30("🇧🇬","Bulgarian"),
  "🇭🇷 Croatia":          VF30("🇭🇷","Croatian"),
  "🇸🇮 Slovenia":         VF30("🇸🇮","Slovenian"),
  "🇪🇪 Estonia":          VF30("🇪🇪","Estonian"),
  "🇱🇻 Latvia":           VF30("🇱🇻","Latvian"),
  "🇱🇹 Lithuania":        VF30("🇱🇹","Lithuanian"),
  "🇷🇸 Serbia":           VF30("🇷🇸","Serbian"),
  "🇲🇪 Montenegro":       VF30("🇲🇪","Montenegrin"),
  "🇲🇰 North Macedonia":  VF30("🇲🇰","North Macedonian"),
  "🇧🇦 Bosnia & Herzegovina":VF30("🇧🇦","Bosnian"),
  "🇦🇱 Albania":          VF30("🇦🇱","Albanian"),
  "🇽🇰 Kosovo":           VF30("🇽🇰","Kosovar"),
  "🇲🇩 Moldova":          VF90("🇲🇩","Moldovan"),
  "🇺🇦 Ukraine":          VF90("🇺🇦","Ukrainian"),
  "🇧🇾 Belarus":          VF90("🇧🇾","Belarusian"),
  "🇷🇺 Russia":           VF90("🇷🇺","Russian"),
  // ── CAUCASUS & CENTRAL ASIA ──
  "🇦🇲 Armenia":          VF90("🇦🇲","Armenian"),
  "🇬🇪 Georgia":          VF90("🇬🇪","Georgian"),
  "🇦🇿 Azerbaijan":       VF90("🇦🇿","Azerbaijani"),
  "🇰🇿 Kazakhstan":       VF90("🇰🇿","Kazakh"),
  "🇰🇬 Kyrgyzstan":       VF90("🇰🇬","Kyrgyz"),
  "🇹🇯 Tajikistan":       VF90("🇹🇯","Tajik"),
  "🇹🇲 Turkmenistan":     VR("🇹🇲","Turkmen"),
  // ── MIDDLE EAST ──
  "🇹🇷 Turkey":           VF30("🇹🇷","Turkish"),
  "🇮🇱 Israel":           VF30("🇮🇱","Israeli"),
  "🇯🇴 Jordan":           EV("🇯🇴","Jordanian"),
  "🇱🇧 Lebanon":          EV("🇱🇧","Lebanese"),
  "🇸🇦 Saudi Arabia":     VF30("🇸🇦","Saudi"),
  "🇦🇪 UAE":              VF30("🇦🇪","Emirati"),
  "🇶🇦 Qatar":            VF30("🇶🇦","Qatari"),
  "🇧🇭 Bahrain":          VF30("🇧🇭","Bahraini"),
  "🇰🇼 Kuwait":           VF30("🇰🇼","Kuwaiti"),
  "🇴🇲 Oman":             VF30("🇴🇲","Omani"),
  "🇮🇶 Iraq":             VR("🇮🇶","Iraqi"),
  "🇮🇷 Iran":             EV("🇮🇷","Iranian"),
  "🇸🇾 Syria":            VR("🇸🇾","Syrian"),
  "🇾🇪 Yemen":            VR("🇾🇪","Yemeni"),
  "🇵🇸 Palestine":        VR("🇵🇸","Palestinian"),
  // ── SOUTH ASIA ──
  "🇮🇳 India":            EV("🇮🇳","Indian"),
  "🇵🇰 Pakistan":         VR("🇵🇰","Pakistani"),
  "🇧🇩 Bangladesh":       VR("🇧🇩","Bangladeshi"),
  "🇳🇵 Nepal":            EV("🇳🇵","Nepali"),
  "🇱🇰 Sri Lanka":        EV("🇱🇰","Sri Lankan"),
  "🇲🇻 Maldives":         EV("🇲🇻","Maldivian"),
  "🇧🇹 Bhutan":           EV("🇧🇹","Bhutanese"),
  "🇦🇫 Afghanistan":      VR("🇦🇫","Afghan"),
  // ── EAST ASIA ──
  "🇨🇳 China":            VF30("🇨🇳","Chinese"),
  "🇯🇵 Japan":            VF30("🇯🇵","Japanese"),
  "🇰🇷 South Korea":      VF30("🇰🇷","South Korean"),
  "🇰🇵 North Korea":      VR("🇰🇵","North Korean"),
  "🇲🇳 Mongolia":         VF30("🇲🇳","Mongolian"),
  "🇹🇼 Taiwan":           VR("🇹🇼","Taiwanese"),
  "🇭🇰 Hong Kong":        EV("🇭🇰","Hong Kong"),
  "🇲🇴 Macau":            VF30("🇲🇴","Macanese"),
  // ── SOUTHEAST ASIA ──
  "🇸🇬 Singapore":        VF30("🇸🇬","Singaporean"),
  "🇲🇾 Malaysia":         VF30("🇲🇾","Malaysian"),
  "🇧🇳 Brunei":           VF30("🇧🇳","Bruneian"),
  "🇹🇭 Thailand":         VF30("🇹🇭","Thai"),
  "🇻🇳 Vietnam":          EV("🇻🇳","Vietnamese"),
  "🇵🇭 Philippines":      EV("🇵🇭","Filipino"),
  "🇮🇩 Indonesia":        VF30("🇮🇩","Indonesian"),
  "🇰🇭 Cambodia":         EV("🇰🇭","Cambodian"),
  "🇱🇦 Laos":             EV("🇱🇦","Laotian"),
  "🇲🇲 Myanmar":          VR("🇲🇲","Myanmar"),
  "🇹🇱 Timor-Leste":      VR("🇹🇱","East Timorese"),
  // ── OCEANIA ──
  "🇦🇺 Australia":        VF30("🇦🇺","Australian"),
  "🇳🇿 New Zealand":      VF30("🇳🇿","New Zealand"),
  "🇫🇯 Fiji":             EV("🇫🇯","Fijian"),
  "🇵🇬 Papua New Guinea": VR("🇵🇬","Papua New Guinean"),
  "🇸🇧 Solomon Islands":  EV("🇸🇧","Solomon Islander"),
  "🇻🇺 Vanuatu":          EV("🇻🇺","Vanuatuan"),
  "🇼🇸 Samoa":            EV("🇼🇸","Samoan"),
  "🇹🇴 Tonga":            EV("🇹🇴","Tongan"),
  "🇰🇮 Kiribati":         EV("🇰🇮","I-Kiribati"),
  "🇳🇷 Nauru":            EV("🇳🇷","Nauruan"),
  "🇵🇼 Palau":            EV("🇵🇼","Palauan"),
  "🇫🇲 Micronesia":       EV("🇫🇲","Micronesian"),
  "🇲🇭 Marshall Islands": EV("🇲🇭","Marshallese"),
  "🇹🇻 Tuvalu":           VR("🇹🇻","Tuvaluan"),
  // ── NORTH AFRICA ──
  "🇪🇬 Egypt":            EV("🇪🇬","Egyptian"),
  "🇲🇦 Morocco":          EV("🇲🇦","Moroccan"),
  "🇹🇳 Tunisia":          EV("🇹🇳","Tunisian"),
  "🇩🇿 Algeria":          EV("🇩🇿","Algerian"),
  "🇱🇾 Libya":            VR("🇱🇾","Libyan"),
  "🇸🇩 Sudan":            VR("🇸🇩","Sudanese"),
  // ── SUB-SAHARAN AFRICA ──
  "🇿🇦 South Africa":     VR("🇿🇦","South African"),
  "🇳🇬 Nigeria":          VR("🇳🇬","Nigerian"),
  "🇰🇪 Kenya":            VR("🇰🇪","Kenyan"),
  "🇬🇭 Ghana":            VR("🇬🇭","Ghanaian"),
  "🇪🇹 Ethiopia":         VR("🇪🇹","Ethiopian"),
  "🇹🇿 Tanzania":         VR("🇹🇿","Tanzanian"),
  "🇺🇬 Uganda":           VR("🇺🇬","Ugandan"),
  "🇿🇼 Zimbabwe":         VR("🇿🇼","Zimbabwean"),
  "🇿🇲 Zambia":           VR("🇿🇲","Zambian"),
  "🇲🇿 Mozambique":       VR("🇲🇿","Mozambican"),
  "🇦🇴 Angola":           EV("🇦🇴","Angolan"),
  "🇨🇩 DR Congo":         VR("🇨🇩","Congolese"),
  "🇨🇬 Congo":            VR("🇨🇬","Congolese"),
  "🇨🇲 Cameroon":         VR("🇨🇲","Cameroonian"),
  "🇸🇳 Senegal":          VR("🇸🇳","Senegalese"),
  "🇨🇮 Côte d'Ivoire":    VR("🇨🇮","Ivorian"),
  "🇲🇱 Mali":             VR("🇲🇱","Malian"),
  "🇧🇫 Burkina Faso":     VR("🇧🇫","Burkinabé"),
  "🇳🇪 Niger":            VR("🇳🇪","Nigerien"),
  "🇹🇩 Chad":             VR("🇹🇩","Chadian"),
  "🇸🇸 South Sudan":      VR("🇸🇸","South Sudanese"),
  "🇸🇴 Somalia":          VR("🇸🇴","Somali"),
  "🇷🇼 Rwanda":           VR("🇷🇼","Rwandan"),
  "🇧🇮 Burundi":          VR("🇧🇮","Burundian"),
  "🇪🇷 Eritrea":          VR("🇪🇷","Eritrean"),
  "🇩🇯 Djibouti":         VR("🇩🇯","Djiboutian"),
  "🇸🇨 Seychelles":       EV("🇸🇨","Seychellois"),
  "🇨🇻 Cape Verde":       EV("🇨🇻","Cape Verdean"),
  "🇲🇺 Mauritius":        EV("🇲🇺","Mauritian"),
  "🇲🇬 Madagascar":       EV("🇲🇬","Malagasy"),
  "🇲🇼 Malawi":           VR("🇲🇼","Malawian"),
  "🇳🇦 Namibia":          VR("🇳🇦","Namibian"),
  "🇧🇼 Botswana":         VR("🇧🇼","Botswanan"),
  "🇸🇿 Eswatini":         VR("🇸🇿","Swazi"),
  "🇱🇸 Lesotho":          VR("🇱🇸","Basotho"),
  "🇬🇦 Gabon":            VR("🇬🇦","Gabonese"),
  "🇬🇶 Equatorial Guinea":VR("🇬🇶","Equatoguinean"),
  "🇸🇹 São Tomé & Príncipe":VR("🇸🇹","São Toméan"),
  "🇬🇼 Guinea-Bissau":    VR("🇬🇼","Bissau-Guinean"),
  "🇬🇳 Guinea":           VR("🇬🇳","Guinean"),
  "🇸🇱 Sierra Leone":     VR("🇸🇱","Sierra Leonean"),
  "🇱🇷 Liberia":          VR("🇱🇷","Liberian"),
  "🇹🇬 Togo":             VR("🇹🇬","Togolese"),
  "🇧🇯 Benin":            VR("🇧🇯","Beninese"),
  "🇬🇲 Gambia":           VR("🇬🇲","Gambian"),
  "🇲🇷 Mauritania":       VR("🇲🇷","Mauritanian"),
  "🇨🇫 Central African Rep.":VR("🇨🇫","Central African"),
  "🇿🇦 Zimbabwe":         VR("🇿🇦","Zimbabwean"),
  "🇰🇲 Comoros":          VR("🇰🇲","Comorian"),
};
// Remove duplicates silently (last wins), then sort for display
const _visaKeys = [...new Set(Object.keys(VISA_DATA))];
const ROUTES = [
  {from:"Tashkent",to:"Samarkand",mode:"🚆 Afrosiyob Bullet Train",time:"2 hrs",price:"$10–15",freq:"5 daily",tip:"Book on uzrailpass.uz — sells out in peak season (Apr–Oct). The fastest and most scenic option."},
  {from:"Samarkand",to:"Bukhara",mode:"🚆 Sharq Train",time:"2 hrs",price:"$8–12",freq:"3 daily",tip:"Morning trains have the best views of the Kyzylkum steppe. Book in advance."},
  {from:"Bukhara",to:"Khiva",mode:"✈️ Domestic Flight",time:"1 hr",price:"$30–60",freq:"Several weekly",tip:"Book on uzairways.com — prices vary wildly. Saves 4+ hours vs overland."},
  {from:"Bukhara",to:"Khiva",mode:"🚗 Shared Taxi",time:"4–5 hrs",price:"$10–15",freq:"When full",tip:"Departs from the main taxi stand when full (usually 4 people). Ask for 'Xiva'. Very local experience."},
  {from:"Tashkent",to:"Khiva",mode:"✈️ Domestic Flight",time:"1.5 hrs",price:"$40–80",freq:"Daily",tip:"Easiest way to reach Khiva. Book at least 2 weeks ahead for best prices."},
  {from:"Any City",to:"Any City",mode:"🚕 Yandex Go (Uber)",time:"Varies",price:"Metered",freq:"Always",tip:"Install before arriving. Far cheaper than street taxis, GPS-tracked, no haggling. Works in all major cities."},
];
const SEASONS = [
  {season:"Spring",months:"March–May",temp:"15–25°C / 59–77°F",icon:"🌸",rating:5,desc:"The absolute best time. Mild temperatures, wildflowers, and Navruz festival on March 21. Sights are vibrant without crushing heat. Book early — it's the most popular season."},
  {season:"Early Summer",months:"June",temp:"25–35°C / 77–95°F",icon:"☀️",rating:4,desc:"Still pleasant in June. Getting warmer but very manageable. Great light for photography. Crowds starting to build at peak sites. Pack sunscreen."},
  {season:"Peak Summer",months:"July–August",temp:"35–44°C / 95–111°F",icon:"🔥",rating:2,desc:"Extremely hot. Not recommended unless heat-acclimatized. Sightseeing is only possible before 10am and after 5pm. Carry electrolytes and stay hydrated constantly."},
  {season:"Autumn",months:"Sept–October",temp:"18–28°C / 64–82°F",icon:"🍂",rating:5,desc:"The second golden season. Harvest time — bazaars overflow with melons, grapes, pomegranates and dried fruits. Perfect golden light for photography."},
  {season:"Late Autumn",months:"November",temp:"5–15°C / 41–59°F",icon:"🍁",rating:3,desc:"Cooling down quickly. Fewer crowds, lower prices. Some outdoor restaurants close. Bring a warm layer — mornings and evenings are cold but sights are beautiful."},
  {season:"Winter",months:"December–February",temp:"-5–5°C / 23–41°F",icon:"❄️",rating:3,desc:"Cold and sometimes snowy — but magical. Zero tourists. Locals are extraordinarily hospitable in winter. Blue domes against white snow are unforgettable photographs."},
];
const PACKING = {
  "Clothing & Modesty":[
    {item:"Lightweight long pants (both genders required at mosques)",key:"p1"},
    {item:"Tops covering shoulders (for religious sites)",key:"p2"},
    {item:"Women: headscarf or large scarf for mosques",key:"p3"},
    {item:"Comfortable walking shoes (cobblestones everywhere)",key:"p4"},
    {item:"Light jacket for evenings (even in summer)",key:"p5"},
    {item:"Layers for autumn/spring — mornings are cool",key:"p6"},
  ],
  "Sun & Health":[
    {item:"SPF 50+ sunscreen (Central Asian sun is brutal)",key:"p7"},
    {item:"Wide-brim hat or cap",key:"p8"},
    {item:"Sunglasses (UV protection)",key:"p9"},
    {item:"Electrolyte sachets for hot days",key:"p10"},
    {item:"Basic first aid + stomach meds (new foods and water)",key:"p11"},
    {item:"Hand sanitizer (not always available at bazaars)",key:"p12"},
  ],
  "Tech & Practical":[
    {item:"Power adapter Type C/F (EU-style, 220V)",key:"p13"},
    {item:"Portable battery bank",key:"p14"},
    {item:"Download Yandex Go app BEFORE arriving",key:"p15"},
    {item:"Offline maps: maps.me downloaded for UZ",key:"p16"},
    {item:"USD or EUR cash for small towns and bazaars",key:"p17"},
    {item:"Google Translate with Uzbek offline downloaded",key:"p18"},
  ],
  "For the Bazaars":[
    {item:"Reusable bag (markets restrict single-use plastic)",key:"p19"},
    {item:"Small denomination USD bills for bargaining",key:"p20"},
    {item:"Empty space in luggage for suzani, ceramics & spices",key:"p21"},
    {item:"Camera or phone with good camera (you'll shoot constantly)",key:"p22"},
  ],
};
const BUDGET = [
  {level:"Budget",icon:"🎒",daily:"$25–40",stay:"Guesthouses & hostels ($10–20/night)",eat:"Street food & local chaikhanas",get:"Trains & shared taxis",tips:["Eat where locals eat — $1 plov is better than $15 tourist plov","Book trains online in advance — saves $5–8 per leg","Free entry: Lyabi-Hauz, Amir Temur Square, Registan (exterior)","Stay in family guesthouses — they often cook breakfast included"]},
  {level:"Mid-Range",icon:"🧳",daily:"$60–100",stay:"3–4 star hotels ($40–80/night)",eat:"Restaurants + some street food",get:"Trains + occasional taxi",tips:["The sweet spot — comfort without tourist-trap pricing","Book hotels 2+ weeks in advance for April–October peak season","Try one splurge meal per city (e.g. Emirhan Samarkand rooftop)","Consider hiring a local guide for 1 day per city ($40–60)"]},
  {level:"Luxury",icon:"✈️",daily:"$200+",stay:"Hilton, Hyatt, boutique hotels ($120–300+)",eat:"Fine dining + rooftop bars",get:"Private transfers & drivers",tips:["Hilton Samarkand Regency and Hyatt Tashkent are genuinely world-class","Private guides cost $80–150/day and add enormous depth to the experience","Consider a hot air balloon over Samarkand at sunrise ($150–200)","Book the Night Show at Registan (light projections) from your hotel"]},
];

export { VISA_DATA, ROUTES, SEASONS, PACKING, BUDGET };

export const PHRASES = {
  "Greetings": [
    { uz: "Assalomu alaykum", ru: "Здравствуйте (Zdravstvuyte)", en: "Hello" },
    { uz: "Salom", ru: "Привет (Privet)", en: "Hi" },
    { uz: "Xayr", ru: "До свидания (Do svidaniya)", en: "Goodbye" },
    { uz: "Rahmat", ru: "Спасибо (Spasibo)", en: "Thank you" },
    { uz: "Iltimos", ru: "Пожалуйста (Pozhaluysta)", en: "Please" },
    { uz: "Kechirasiz", ru: "Извините (Izvinite)", en: "Excuse me / Sorry" }
  ],

  "Getting Around": [
    { uz: "Bu qayerda?", ru: "Где это? (Gde eto?)", en: "Where is this?" },
    { uz: "…ga boring", ru: "Поехали в… (Poyekhali v…)", en: "Go to…" },
    { uz: "To‘xtating", ru: "Остановите (Ostanovite)", en: "Stop here" },
    { uz: "Piyoda yurish", ru: "Пешком (Peshkom)", en: "On foot" },
    { uz: "Chap", ru: "Налево (Nalevo)", en: "Left" },
    { uz: "O‘ng", ru: "Направо (Napravo)", en: "Right" },
    { uz: "To‘g‘ri", ru: "Прямо (Pryamo)", en: "Straight ahead" }
  ],

  "Food & Restaurants": [
    { uz: "Bu nima?", ru: "Что это? (Chto eto?)", en: "What is this?" },
    { uz: "Juda mazali!", ru: "Очень вкусно! (Ochen vkusno!)", en: "Very delicious!" },
    { uz: "Plov kerak", ru: "Плов, пожалуйста", en: "Plov please" },
    { uz: "Hisob-kitob", ru: "Счёт, пожалуйста (Schyot)", en: "The bill please" },
    { uz: "Vegetarian ovqat", ru: "Без мяса (Bez myasa)", en: "Vegetarian food" },
    { uz: "Suv", ru: "Вода (Voda)", en: "Water" },
    { uz: "Choy", ru: "Чай (Chay)", en: "Tea" }
  ],

  "Shopping": [
    { uz: "Bu nech pul?", ru: "Сколько стоит?", en: "How much is this?" },
    { uz: "Arzonroq bo‘ladimi?", ru: "Можно дешевле?", en: "Can it be cheaper?" },
    { uz: "Qimmat", ru: "Дорого", en: "Expensive" },
    { uz: "Arzon", ru: "Дешево", en: "Cheap" }
  ]
};