const sights = [
{id:"s1",name:"Registan Square",type:"place",icon:"🏛️",lat:39.6546,lng:66.9758,rating:4.8,reviews:2847,markerColor:"#1A6B8A",wiki:"Registan",desc:"Three madrasas forming the most magnificent ensemble in all of Central Asia. The tilework, mosaics, and sheer scale is unlike anything in the world. Built between 1417–1660.",tip:"Book a Night Show ticket — light projections transform the domes into something magical.",hours:"8am–8pm daily",fee:"100,000 UZS (~$8)"},
      {id:"s2",name:"Gur-i Amir Mausoleum",type:"place",icon:"☪️",lat:39.6485,lng:66.9692,rating:4.7,reviews:1923,markerColor:"#1A6B8A",wiki:"Gur-e-Amir",desc:"Tamerlane's tomb — a sky-blue ribbed dome and jade portal. One of the most moving sacred sites in Central Asia, built in 1404. The interior is hushed and golden.",tip:"Visit in the evening — no crowds and perfect amber light.",hours:"8am–7pm daily",fee:"75,000 UZS"},
      {id:"s3",name:"Shah-i-Zinda Necropolis",type:"place",icon:"✨",lat:39.6621,lng:66.9879,rating:4.8,reviews:3102,markerColor:"#1A6B8A",wiki:"Shah-i-Zinda",desc:"A sacred avenue of turquoise-tiled mausoleums climbing a hillside. The most spiritually charged site in Uzbekistan — pilgrims and travelers come from across the world.",tip:"Arrive at 7am when it opens — golden light and zero tourists.",hours:"7am–10pm daily",fee:"80,000 UZS"},
      {id:"s4",name:"Bibi-Khanym Mosque",type:"place",icon:"🕌",lat:39.6607,lng:66.9797,rating:4.6,reviews:1548,markerColor:"#1A6B8A",wiki:"Bibi-Khanym_Mosque",desc:"Built by Tamerlane after his Indian conquest. A 38-meter portal of turquoise tiles and Quranic inscriptions. Once the largest mosque in the Islamic world.",tip:"Dress modestly — shoulders and knees covered. Entry is straightforward.",hours:"7am–10pm daily",fee:"75,000 UZS"},
      {id:"s5",name:"Ulugh Beg Observatory",type:"place",icon:"🔭",lat:39.6748,lng:67.0056,rating:4.3,reviews:876,markerColor:"#1A6B8A",wiki:"Ulugh_Beg_Observatory",desc:"15th-century observatory of the scholar-prince Ulugh Beg. The giant underground sextant trench mapped stars with astounding accuracy 500 years before modern telescopes.",tip:"Pair with the museum — the history of Islamic astronomy will fascinate you.",hours:"8am–7pm daily",fee:"75,000 UZS"},
      {id:"s6",name:"Siab Bazaar",type:"place",icon:"🛍️",lat:39.6605,lng:66.9820,rating:4.5,reviews:2210,markerColor:"#1A6B8A",wiki:"Siab_Bazaar",desc:"The sprawling local market next to Bibi-Khanym. Spices, dried fruits, fresh non bread from the tandoor, and the real pulse of Samarkand — not the tourist version.",tip:"Go on a Saturday. Try the non bread hot from the tandoor — 2,000 UZS.",hours:"7am–5pm daily",fee:"Free"},
      {id:"s7",name:"Amir Temur Monument",type:"place",icon:"🗿",lat:39.6504,lng:66.9649,rating:4.7,reviews:1201,markerColor:"#1A6B8A",wiki:"Amir_Timur_Museum",desc:"Imposing bronze seated statue of Tamerlane at the heart of Samarkand, lit dramatically at night against a backdrop of fountains and the old city skyline.",tip:"Great photo spot at golden hour and after dark when fully illuminated.",hours:"Open 24 hours",fee:"Free"},
];

export default sights;
