const sights = [
{id:"k1",name:"Ichan Kala (Old City)",type:"place",icon:"🏙️",lat:41.3781,lng:60.3593,rating:4.7,reviews:1876,markerColor:"#6B4226",wiki:"Ichan_Kala",desc:"The UNESCO-listed walled inner city — 400 buildings, 2.2km of walls, every alley unchanged for centuries. The world's most intact medieval Islamic city.",tip:"Stay inside the walls. Walking empty alleys at midnight is truly otherworldly.",hours:"9am–7pm (walls always open)",fee:"150,000 UZS (all sites)"},
      {id:"k2",name:"Kalta Minor Minaret",type:"place",icon:"🔵",lat:41.3783,lng:60.3580,rating:4.8,reviews:1432,markerColor:"#6B4226",wiki:"Kalta_Minor",desc:"The unfinished 'Short Minaret' — intended to be the tallest in the world but halted when its patron died in battle. Vibrant turquoise tiles make it unmistakable.",tip:"Best photographed from the Ata Gate in early morning light.",hours:"Open 24 hours",fee:"Included in city pass"},
      {id:"k3",name:"Toshhovli Palace",type:"place",icon:"👑",lat:41.3784,lng:60.3617,rating:4.8,reviews:1102,markerColor:"#6B4226",wiki:"Toshhovli_Palace",desc:"The Khan's 19th-century palace with 150 rooms across three courtyards. The blue mosaic tilework in the harem rooms is the finest craftsmanship in all of Khiva.",tip:"Come back in the afternoon after tour groups leave — you'll have the halls to yourself.",hours:"Museum hours",fee:"Included in city pass"},
      {id:"k4",name:"Islam Khoja Minaret",type:"place",icon:"🗼",lat:41.3766,lng:60.3601,rating:4.6,reviews:876,markerColor:"#6B4226",wiki:"Islam_Khoja_Minaret",desc:"The tallest minaret in Khiva at 56 meters, built in 1908. Climb 99 steep steps for spectacular views over the terracotta rooftops of Ichan Kala.",tip:"Climb first thing in the morning before the heat builds in summer.",hours:"8am–6pm daily",fee:"Included in city pass"},
      {id:"k5",name:"Kuhna Ark (Old Citadel)",type:"place",icon:"🏯",lat:41.3794,lng:60.3579,rating:4.6,reviews:923,markerColor:"#6B4226",wiki:"Kuhna_Ark",desc:"The Khan's original fortress with watchtowers, throne room, stables and a mint. Climb the walls for sweeping views over the white city below.",tip:"The sunset view from the walls over the old city is the single best view in Khiva.",hours:"9am–5pm daily",fee:"Included in city pass"},
      {id:"k6",name:"Juma Mosque",type:"place",icon:"🕌",lat:41.3775,lng:60.3599,rating:4.7,reviews:1043,markerColor:"#6B4226",wiki:"Juma_Mosque,_Khiva",desc:"A hypostyle forest of 213 unique wooden carved columns, some dating to the 10th century. Unlike any mosque you've seen — dim, cool, and hauntingly beautiful.",tip:"Look for the oldest columns — some have ancient Zoroastrian symbols carved into them.",hours:"9am–6pm daily",fee:"Included in city pass"},
];

export default sights;
