const sights = [
{id:"t1",name:"Amir Temur Square",type:"place",icon:"🏛️",lat:41.2994,lng:69.2401,rating:4.6,reviews:1876,markerColor:"#4A148C",wiki:"Amir_Timur_Square",desc:"The grand central square of Tashkent — manicured gardens, fountain pools, and the equestrian statue of Tamerlane. The city's social heart and the best people-watching spot.",tip:"Come at night — the square is beautifully lit and Tashkent youth gather here.",hours:"Open 24 hours",fee:"Free"},
      {id:"t2",name:"Chorsu Bazaar",type:"place",icon:"🛒",lat:41.3200,lng:69.2347,rating:4.5,reviews:2341,markerColor:"#4A148C",wiki:"Chorsu_Bazaar",desc:"The ancient domed bazaar at the heart of old Tashkent. Beneath the huge blue dome: spices, herbs, dried fruits, fresh plov, and the real soul of the city.",tip:"Go early morning (7–9am) when it's freshest. Bring cash only.",hours:"7am–6pm daily",fee:"Free"},
      {id:"t3",name:"Hazrat Imam Complex",type:"place",icon:"☪️",lat:41.3271,lng:69.2613,rating:4.7,reviews:1543,markerColor:"#4A148C",wiki:"Hazrat_Imam_Complex",desc:"Uzbekistan's holiest Islamic site — home to the world's oldest Quran manuscript, kept in an ancient library. The mosque and square are magnificent.",tip:"Dress modestly. The library with the Uthman Quran is inside — ask permission.",hours:"8am–6pm (closed Fri noon)",fee:"Free"},
      {id:"t4",name:"State Museum of History",type:"place",icon:"🏛️",lat:41.3107,lng:69.2868,rating:4.3,reviews:876,markerColor:"#4A148C",wiki:"State_Museum_of_History",desc:"Uzbekistan's largest museum traces the Silk Road from prehistory through Soviet times. The Islamic art and Zoroastrian artifact collections are extraordinary.",tip:"The basement halls have Hellenistic-era Bactrian gold — not to be missed.",hours:"10am–6pm (closed Mon)",fee:"30,000 UZS"},
      {id:"t5",name:"Tashkent Metro",type:"place",icon:"🚇",lat:41.2995,lng:69.2399,rating:4.8,reviews:3210,markerColor:"#4A148C",wiki:"Tashkent_Metro",desc:"The most ornate metro system in the world — each station is a unique Soviet-era masterpiece with marble, mosaics, chandeliers, and intricate craftsmanship.",tip:"Buy a metro card (15,000 UZS) and ride every single line — 3 lines, 29 stations, all different.",hours:"5:30am–12am daily",fee:"2,000 UZS/ride"},
      {id:"t6",name:"Earthquake Memorial Park",type:"place",icon:"🌿",lat:41.3050,lng:69.2710,rating:4.4,reviews:654,markerColor:"#4A148C",wiki:"Earthquake_Memorial_Park",desc:"Beautiful park commemorating the 1966 earthquake that destroyed Tashkent. The Soviet-era solidarity architecture around it tells an extraordinary story.",tip:"Walk through the old neighborhood at dusk — locals gather for tea.",hours:"Open 24 hours",fee:"Free"},
];

export default sights;
